# Dialyzer warnings that are NOT defects (issue #73). Every entry says why. A warning not
# listed here fails ./ci.sh. Entries are {file, warning_type}, so an ordinary edit that
# shifts line numbers does not churn this file; the reason names the construct.
#
# Real defects dialyzer found were FIXED, not listed: SearchLive's org-switcher return path
# (taken from the params map by a URI-only function, so always nil), a dead `{:ok, decided}`
# arm in AgentReads.decide/3, and — in samen_core — the Samen.Scope actor type whose
# strictness made every `:: Samen.Scope.t()` spec here an invalid contract.
[
  # ── Fail-closed catch-all clauses dialyzer's local inference thinks unreachable: the last
  #    line for params, session data and provider/webhook payloads that come from outside
  #    this module's inference. Deleting them turns a bounded answer into a crash.
  {"lib/samen/web/ai/agent_reads.ex", :pattern_match_cov},
  {"lib/samen/web/ai/server.ex", :pattern_match_cov},
  {"lib/samen/web/auth/oidc_controller.ex", :pattern_match_cov},
  {"lib/samen/web/crm/dashboard_live.ex", :pattern_match_cov},
  {"lib/samen/web/current_org.ex", :pattern_match_cov},
  {"lib/samen/web/reads.ex", :pattern_match_cov},
  {"lib/samen/web/webhook/ingress.ex", :pattern_match_cov},

  # ── Ash aggregates: `Ash.sum!/3` / `Ash.avg!/3` / `Ash.count!/2` are spec'd as returning a
  #    number, but at runtime a sum over no rows is nil, a Money column sums to %Money{} and
  #    an avg over a numeric column is a %Decimal{}. The `|| 0` fallbacks and the
  #    Decimal/Money clauses that dialyzer calls unreachable are what make those real values
  #    render.
  {"lib/samen/web/account_health.ex", :guard_fail},
  {"lib/samen/web/billing/reads.ex", :guard_fail},
  {"lib/samen/web/crm/reads.ex", :guard_fail},
  {"lib/samen/web/crm/reads.ex", :pattern_match},
  {"lib/samen/web/reads.ex", :pattern_match},
  {"lib/samen/web/support/reads.ex", :pattern_match},
  {"lib/samen/web/support/reads.ex", :call},

  # ── Defensive `||` fallbacks after calls spec'd non-nil: the KB article list when no KB
  #    mount is wired (portal_kb_live), and an agent's display name when its decoded full
  #    name is absent (ticket_live).
  {"lib/samen/web/support/portal_kb_live.ex", :guard_fail},
  {"lib/samen/web/support/ticket_live.ex", :guard_fail},

  # ── Generated by `use` on line 1 (a macro clause), not code in this file.
  {"lib/samen/web/operator/fleet_resolve_live.ex", :pattern_match}
]
