defmodule Demo.CmsScope do
  @moduledoc """
  The Demo host's CMS domain — mounted from the `samen_core` CMS scope
  blueprint (ADR-004; T3.5).

  One `use Samen.Scopes.Cms` expands into seven host-owned resources
  (`Demo.CmsScope.{Page,Post,Block,Media,Navigation,SeoMeta,ContentVersion}`),
  each a normal `use Samen.Resource` in the DEMO's `otp_app`/`repo`, so:

    * their columns are catalogued in the DEMO's `tam_table`/`fld_field`
      (the `AddCmsScope` migration's `catalog_sync/1`);
    * the DEMO's unchanged verifiers scan them;
    * no PII is vault-routed (the CMS scope has no 🔒 objects);
    * org-scope + RBAC policies are inherited, not re-authored;
    * the draft→publish workflow (page/post status) is enforced at the policy level.

  ## Non-PII classification (mask-unknown-by-default proof)

  The CMS scope's free-text fields (`title`, `body`, `slug`, `description`,
  `alt_text`, `label`) are deliberately classified as non-PII. `csm_seo_meta`'s
  `description` field is the load-bearing registration: free-text "description"
  fields could be questioned by an auditor. The explicit `non_pii!` registration
  with distinct-reviewer sign-off (see `Demo.CmsScope.NonPiiSetup`) proves the
  mask-unknown-by-default discipline was applied — the field was consciously
  evaluated and cleared, not silently assumed safe.

  ## Content versioning

  `ContentVersion` is append-only (no :update/:destroy actions). Page and Post
  publish/archive actions are expected to call
  `Demo.CmsScope.ContentVersion.create_version/2` explicitly to record immutable
  snapshots. See `Samen.Scopes.Cms.Blueprint.define_content_version/5`.

  ## Smoke usage (T3.5 acceptance: "thin smoke usage per scope proves host-mounting works")

  The `Demo.CmsScope.Smoke` module (below) exercises one round-trip per resource —
  a page, a post, a block, a media asset, a navigation item, seo_meta, and a content
  version — confirming the host-mount and the immutable-history mechanism work
  end-to-end against a real Postgres DB.
  """
  use Ash.Domain, validate_config_inclusion?: false

  use Samen.Scopes.Cms,
    otp_app: :demo,
    repo: Demo.Repo,
    namespace: Demo.CmsScope
end

defmodule Demo.CmsScope.NonPiiSetup do
  @moduledoc """
  Runtime registration of deliberate non-PII columns in the CMS scope.

  Called from test setup and from the demo seed task. These registrations
  fulfill the T3.5 requirement to "prove mask-unknown-by-default classification
  on free-text fields is handled (classified non-PII deliberately, documented)".

  ## Why registration is needed

  `Samen.NonPii.register/1` requires **distinct reviewers** (the same distinct-party
  discipline as reveal grants). The `pii_classify` verifier (C4) checks the registry
  at build time and fails the build on any flagged column without a valid registration.

  None of the CMS free-text fields (`title`, `body`, `description`, `alt_text`,
  `label`) are flagged by C4 because their names are not in the PII name-token list
  (`ssn·dob·mrn·cdl·tax_id·email·phone·address·…`). However, we register
  `csm_seo_meta.csm_description` explicitly because:

    1. "description" is a common free-text field that auditors flag in reviews.
    2. Its explicit registration is the load-bearing demonstration that the
       mask-unknown-by-default discipline (D9) was APPLIED, not assumed.
    3. The distinct-reviewer check proves two people agreed this is not PII.

  ## Registered columns

  | Table        | Column          | Rationale                                     |
  |--------------|-----------------|-----------------------------------------------|
  | csm_seo_meta | csm_description | Authored marketing copy — consciously cleared |

  """

  @doc """
  Register the CMS non-PII columns. Idempotent — safe to call multiple times.
  Returns `:ok` or `{:error, reason}`.
  """
  def register_all do
    # csm_seo_meta.csm_description — the load-bearing non-PII demonstration.
    # Two distinct reviewers required (fail closed on self-review).
    case Samen.NonPii.register(%{
           table_name: "csm_seo_meta",
           column_name: "csm_description",
           cleared_by: "T3.5-scope-author",
           reviewed_by: "T3.5-gate-reviewer",
           reason:
             "SEO meta description is authored marketing copy generated by the product operator, " <>
               "not a subject personal identifier. It describes pages/posts, not natural persons. " <>
               "Evaluated under D9 mask-unknown-by-default: consciously cleared as non-PII " <>
               "with distinct-reviewer sign-off (T3.5 CMS scope).",
           subject_column: "csm_org_id",
           redaction: "[REDACTED_CONTENT]"
         }) do
      {:ok, _} -> :ok
      {:error, reason} -> {:error, reason}
    end
  end
end

defmodule Demo.CmsScope.Smoke do
  @moduledoc """
  Thin smoke usage for the CMS scope. Exercises one round-trip per resource,
  confirming the host-mount and core mechanics work end-to-end.

  Called from tests (`cms_scope_policy_matrix_test.exs`) to prove:
    * host-mounting works (resources exist, compile, have the right namespace)
    * the org-scope policy is wired (cross-org invisibility)
    * the draft→publish workflow works (admin can publish; member cannot)
    * ContentVersion is append-only (no :update/:destroy)
    * non-PII classification is registered (csm_description)
  """

  alias Demo.CmsScope.{Page, Post, Block, Media, Navigation, SeoMeta, ContentVersion}

  @doc "Create a page in the given org. authorize?: false for seeding."
  def mk_page(org_id, title \\ "Test Page") do
    Page
    |> Ash.Changeset.for_create(:create, %{
      title: title,
      slug: "test-#{:rand.uniform(999_999)}",
      body: "This is the page body.",
      org_id: org_id
    })
    |> Ash.create(authorize?: false)
  end

  @doc "Create a post in the given org."
  def mk_post(org_id, title \\ "Test Post") do
    Post
    |> Ash.Changeset.for_create(:create, %{
      title: title,
      slug: "post-#{:rand.uniform(999_999)}",
      body: "This is the post body.",
      excerpt: "A short excerpt.",
      org_id: org_id
    })
    |> Ash.create(authorize?: false)
  end

  @doc "Create a block (optionally attached to a page)."
  def mk_block(org_id, page_id \\ nil) do
    Block
    |> Ash.Changeset.for_create(:create, %{
      name: "Hero Block",
      block_type: :hero,
      content: %{"heading" => "Welcome", "cta" => "Get Started"},
      org_id: org_id,
      page_id: page_id
    })
    |> Ash.create(authorize?: false)
  end

  @doc "Create a media asset."
  def mk_media(org_id) do
    Media
    |> Ash.Changeset.for_create(:create, %{
      file_name: "hero.jpg",
      content_type: "image/jpeg",
      size_bytes: 204_800,
      storage_key: "uploads/hero-#{:rand.uniform(999_999)}.jpg",
      alt_text: "A hero image for the homepage",
      org_id: org_id
    })
    |> Ash.create(authorize?: false)
  end

  @doc "Create a navigation item (Tier-0 config row)."
  def mk_navigation(org_id) do
    Navigation
    |> Ash.Changeset.for_create(:create, %{
      label: "Home",
      url: "/",
      nav_type: :main,
      position: 0,
      org_id: org_id
    })
    |> Ash.create(authorize?: false)
  end

  @doc "Create SEO meta for a page."
  def mk_seo_meta(org_id, page_id) do
    SeoMeta
    |> Ash.Changeset.for_create(:create, %{
      meta_title: "Test Page | Demo",
      description: "This is a demo page for testing CMS SEO metadata.",
      canonical_url: "https://demo.example/pages/test",
      org_id: org_id,
      page_id: page_id
    })
    |> Ash.create(authorize?: false)
  end

  @doc "Create a content version (append-only)."
  def mk_content_version(org_id, page_id) do
    ContentVersion
    |> Ash.Changeset.for_create(:create_version, %{
      subject_type: "page",
      subject_id: page_id,
      content_snapshot: %{"title" => "Test Page", "body" => "v1 content"},
      status: :draft,
      author_id: org_id,
      version_number: 1,
      change_summary: "Initial draft",
      org_id: org_id
    })
    |> Ash.create(authorize?: false)
  end
end
