# Dialyzer warnings that are NOT defects (issue #73). Every entry says why. A warning not
# listed here fails ./ci.sh. Entries are {file, warning_type}, so an ordinary edit that
# shifts line numbers does not churn this file; the reason names the construct.
#
# Real defects dialyzer found were FIXED, not listed: SessionRevoke.revoke_one/3 (PR #77),
# the Samen.Scope actor type, the Ash.Resource.record/0 → Ash.Resource.Record.t() specs,
# the missing @type t on FieldRow / ObjectRow / Gen.Agent.Spec, Totp.mods, Reset.request's
# mods, ApiKey.expired?'s argument type.
[
  # ── Fail-closed catch-all clauses dialyzer's LOCAL inference thinks unreachable. They are
  #    the deliberate last line for input a caller outside this module's inference can still
  #    send (adapter returns, persisted maps, config). Deleting them would turn a bounded
  #    refusal into a FunctionClauseError at runtime.
  {"lib/mix/tasks/samen.doctor.ex", :pattern_match_cov},
  {"lib/samen/adapter_conformance_case.ex", :pattern_match_cov},
  {"lib/samen/ai/agent/tool_result.ex", :pattern_match_cov},
  {"lib/samen/analytics.ex", :pattern_match_cov},
  {"lib/samen/approvals.ex", :pattern_match_cov},
  {"lib/samen/erasure.ex", :pattern_match_cov},
  {"lib/samen/kms.ex", :pattern_match_cov},
  {"lib/samen/mailbox/sync.ex", :pattern_match_cov},
  {"lib/samen/pii/info.ex", :pattern_match_cov},
  {"lib/samen/scopes/marketing/send_worker.ex", :pattern_match_cov},
  {"lib/samen/transformers/materialize_pii.ex", :pattern_match_cov},

  # ── S3 Object Lock anchor: with the anchor disabled, read_head/1 and list_heads/0 RAISE a
  #    clear operator TODO by design (see the module's "config gate" comment) — never a faked
  #    {:ok, _} and never a silent no-op that would read as a false green to the verifier.
  {"lib/samen/anchor/s3_object_lock.ex", :no_return},

  # ── Ash.sum/3's spec says the result is a number, but over an empty set it returns nil at
  #    runtime (the quota and tally tests exercise exactly that); the {:ok, nil} arm is needed.
  {"lib/samen/billing/quota.ex", :pattern_match},
  {"lib/samen/billing/usage_tally.ex", :pattern_match},

  # ── Generated by `use Oban.Worker` on line 1 (a macro clause), not code in this file.
  {"lib/samen/delivery/lifecycle/email_worker.ex", :pattern_match},

  # ── Defensive guards dialyzer types too narrowly: an atom error kind from a governed
  #    action (enqueue_reminder) and `refs || %{}` over a provider-event map that can be nil
  #    for a malformed persisted event (webhook_dispatch).
  {"lib/samen/automation/actions/enqueue_reminder.ex", :guard_fail},
  {"lib/samen/billing/webhook_dispatch.ex", :guard_fail},

  # ── Ecto.Multi's opaque type: dialyzer reports `Ecto.Multi.insert/update_all` on a Multi
  #    built by Ecto.Multi.new/0 as an opaque violation (a long-standing Ecto/dialyzer false
  #    positive); the transactions run in the erasure, impersonation and reveal suites.
  {"lib/samen/erasure.ex", :call_without_opaque},
  {"lib/samen/impersonation/sessions.ex", :call_without_opaque},
  {"lib/samen/reveal/grants.ex", :call_without_opaque}
]
